config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :transactions
  resources :my_wallets
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'find_users', to: 'pages#find_users'
end

app/views/pages/home.html.erb
<h1 style="text-align: center;">Raiz Internal Wallet Transactional System</h1>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>


<div class="card" style="width: 18rem; width: 100%; background-color: #dfe7f5; margin-top: 40px; margin-bottom: 40px;">
  <div class="card-body" style="text-align: center">
    <h3 class="card-title" style="margin-top: 20px">Transfer Actions</h3>
    <%= form_tag(find_users_path, method: 'get', id: 'search-form') do %>
      <%= hidden_field_tag :user, params[:user], value: params[:user] %>
      <div class="row">
        <div class="input-field col 6">
          <label for="search" style="margin-top: 20px"><i class="material-icons"></i>Enter Sender User ID</label>
          <%= text_field_tag :sender, params[:sender] %>
          <label for="search" style="margin-top: 20px"><i class="material-icons"></i>Enter Recipient User ID</label>
          <%= text_field_tag :recipient, params[:recipient] %>
          <label for="search" style="margin-top: 20px"><i class="material-icons"></i>Enter Amount</label>
          <%= text_field_tag :amount, params[:amount] %>
        </div>
      </div>
      <%= submit_tag "Create Transaction", class: 'btn btn-primary', style: 'margin: 20px' %>
    <% end %>
  </div>
</div>

<br>
<h3>List of Users</h3>
<table class="table">
  <thead>
  <tr>
    <th scope="col">User ID</th>
    <th scope="col">Name</th>
    <th scope="col">Balance</th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.name %></td>
      <td><%= sprintf('%.2f', user.display_balance) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>
<h3>List of Transactions</h3>
<table class="table">
  <thead>
  <tr>
    <th scope="col">ID</th>
    <th scope="col">Name</th>
    <th scope="col">User</th>
    <th scope="col">Source wallet</th>
    <th scope="col">Target wallet</th>
    <th scope="col">Amount</th>
  </tr>
  </thead>
  <tbody>
  <% @transactions.each do |transaction| %>
    <tr>
      <td><%= transaction.id %></td>
      <td><%= transaction.name %></td>
      <td><%= transaction.user_id %></td>
      <td><%= transaction.source_wallet %></td>
      <td><%= transaction.target_wallet %></td>
      <td><%= sprintf('%.2f', transaction.amount) %></td>
    </tr>
  <% end %>
  </tbody>
</table>