config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :transactions
  resources :my_wallets
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'find_users', to: 'pages#find_users'
end

app/models/my_wallet.rb
class MyWallet < ApplicationRecord
  belongs_to :user, :class_name => 'User', :foreign_key => 'user_id'
  validates :balance, numericality: { greater_than_or_equal_to: 0, message: "Balance must be non-negative." }
end

app/controllers/my_wallets_controller.rb
class MyWalletsController < ApplicationController
  before_action :set_my_wallet, only: [:show, :edit, :update, :destroy]

  # GET /my_wallets
  # GET /my_wallets.json
  def index
    @my_wallets = MyWallet.all
  end

  # GET /my_wallets/1
  # GET /my_wallets/1.json
  def show
  end

  # GET /my_wallets/new
  def new
    @my_wallet = MyWallet.new
  end

  # GET /my_wallets/1/edit
  def edit
  end

  # POST /my_wallets
  # POST /my_wallets.json
  def create
    @my_wallet = MyWallet.new(my_wallet_params)

    respond_to do |format|
      if @my_wallet.save
        format.html { redirect_to @my_wallet, notice: 'My wallet was successfully created.' }
        format.json { render :show, status: :created, location: @my_wallet }
      else
        format.html { render :new }
        format.json { render json: @my_wallet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_wallets/1
  # PATCH/PUT /my_wallets/1.json
  def update
    respond_to do |format|
      if @my_wallet.update(my_wallet_params)
        format.html { redirect_to @my_wallet, notice: 'My wallet was successfully updated.' }
        format.json { render :show, status: :ok, location: @my_wallet }
      else
        format.html { render :edit }
        format.json { render json: @my_wallet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_wallets/1
  # DELETE /my_wallets/1.json
  def destroy
    @my_wallet.destroy
    respond_to do |format|
      format.html { redirect_to my_wallets_url, notice: 'My wallet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_wallet
      @my_wallet = MyWallet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def my_wallet_params
      params.require(:my_wallet).permit(:user_id, :balance)
    end
end

app/helpers/my_wallets_helper.rb
module MyWalletsHelper
end

app/views/my_wallets/_form.html.erb
<%= form_with(model: my_wallet, local: true) do |form| %>
  <% if my_wallet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(my_wallet.errors.count, "error") %> prohibited this my_wallet from being saved:</h2>

      <ul>
        <% my_wallet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :balance %>
    <%= form.text_field :balance %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/my_wallets/edit.html.erb
<h1>Editing My Wallet</h1>

<%= render 'form', my_wallet: @my_wallet %>

<%= link_to 'Show', @my_wallet %> |
<%= link_to 'Back', my_wallets_path %>

app/views/my_wallets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Wallets</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Balance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @my_wallets.each do |my_wallet| %>
      <tr>
        <td><%= my_wallet.user_id %></td>
        <td><%= my_wallet.balance %></td>
        <td><%= link_to 'Show', my_wallet %></td>
        <td><%= link_to 'Edit', edit_my_wallet_path(my_wallet) %></td>
        <td><%= link_to 'Destroy', my_wallet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New My Wallet', new_my_wallet_path %>

app/views/my_wallets/new.html.erb
<h1>New My Wallet</h1>

<%= render 'form', my_wallet: @my_wallet %>

<%= link_to 'Back', my_wallets_path %>

app/views/my_wallets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @my_wallet.user_id %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @my_wallet.balance %>
</p>

<%= link_to 'Edit', edit_my_wallet_path(@my_wallet) %> |
<%= link_to 'Back', my_wallets_path %>